// Formulario AFA Ingreso adaptado - Sin queries SQL, con opciones hardcodeadas
export const afaIngresoForm = {
	id: 2,
	name: 'Factibilidad',
	template: [[5, '1fr 1fr 1fr 1fr 1fr'], '1fr', '1fr', '1fr', '1fr', '1fr', '1fr', '1fr', '1fr', '1fr'],
	observers: [
		{ name: 'porcentajeVenta12M', type: 'basic', formula: '(venta12M / tirada) * 100' },
		{ name: 'digitalNetSale', type: 'basic', formula: 'pvpDigital * venta12MDigital' },
		{ name: 'graphicNetSale', type: 'basic', formula: 'pvp * venta12M' },
		{ name: 'totalNetSale', type: 'basic', formula: 'graphicNetSale + digitalNetSale' },
		{ name: 'digitalDiscount', type: 'basic', formula: 'digitalNetSale * (porcentajeDescuentoDigital / 100)' },
		{ name: 'graphicDiscount', type: 'basic', formula: 'graphicNetSale * (porcentajeDescuento / 100 )' },
		{ name: 'totalDiscount', type: 'basic', formula: 'graphicDiscount + digitalDiscount' },
		{ name: 'ventaLiquida', type: 'basic', formula: 'totalNetSale - totalDiscount' },
		{
			name: 'costoUnitario',
			type: 'basic',
			formula: '(inversionProduccion + ((materialAlmacen + materialConsignado) * ultimoCostoStock)) / (tirada + materialAlmacen + materialConsignado)',
		},
		{ name: 'porcentajeCostoUnitario', type: 'basic', formula: '(costoUnitario / pvp) * 100' },
		{ name: 'multiplicador', type: 'basic', formula: 'pvp / costoUnitarioMultiplicador' },
		{ name: 'ventaNetaTotal', type: 'basic', formula: '(pvp * venta12M) + (pvpDigital * venta12MDigital)' },
		{
			name: 'margenBrutoTotal',
			formula: '(pvp * (1 - (porcentajeDescuento / 100) - (porcentajeCostoUnitario / 100) - (porcentajeDerechoAutor / 100 )) * venta12M) + (pvpDigital * (1 - (porcentajeDescuentoDigital / 100) - (porcentajeDerechoAutorDigital / 100)) * venta12MDigital)',
		},
		{ name: 'porcentajeMargenBruto', type: 'basic', formula: '(margenBrutoTotal / ventaNetaTotal) * 100' },
	],
	fields: [
		{
			name: 'claveTipoVenta',
			type: 'buttonGroup',
			label: 'Tipo de venta:',
			options: [
				{ value: 'REG', label: 'Regular' },
				{ value: 'INS', label: 'Institucional' },
				{ value: 'ESP', label: 'Especial' },
			],
			disabledOptions: ['INS'],
			value: 'REG',
		},
		{
			type: 'select',
			name: 'business-unity',
			label: 'Unidad de Negocio: ',
			options: [
				{ value: '1', label: 'Unidad de Negocio 1' },
				{ value: '2', label: 'Unidad de Negocio 2' },
				{ value: '3', label: 'Unidad de Negocio 3' },
			],
			value: '',
			autoSelectFirst: true,
		},
		{
			name: 'codigoPlanEditorial',
			type: 'select',
			label: 'Plan editorial: ',
			value: '050',
			selectedOptionLabel: '050 - Plan Editorial 2024',
			notTrigger: true,
			properties: ['selectedOptionLabel'],
			options: [
				{ value: '050', label: '050 - Plan Editorial 2024' },
				{ value: '051', label: '051 - Plan Editorial 2025' },
				{ value: '052', label: '052 - Plan Editorial 2026' },
			],
		},
		{
			name: 'description',
			type: 'text',
			label: 'Descripcion: ',
			value: '',
			dependentOn: [
				{
					fields: ['codigoPlanEditorial'],
					callback: 'copyValue',
					to: 'description',
					field: 'codigoPlanEditorial',
					from: 'codigoPlanEditorial',
					propertyToCopy: 'selectedOptionLabel',
					valueSeparator: ' - ',
				},
			],
		},
		{ name: 'requestId', label: 'Solicitud: ', disabled: true, value: 'afa-', type: 'text' },
		{ type: 'hr', name: 'hr' },
		{
			type: 'wrapper',
			control: 'div',
			name: 'second-part',
			className: 'second-part',
			template: [[3, '1fr 1fr 1fr'], [3, '1fr 1fr 1fr'], [3, '1fr 1fr 1fr'], '1fr', '1fr'],
			fields: [
				{
					type: 'wrapper',
					control: 'tooltip',
					name: 'tooltip-average-pvp',
					template: ['1fr'],
					tooltipData: {
						title: 'PVP Promedio = Sumatoria [(PVP * venta (12 meses)) Gráfico + (PVP * venta (12 meses)) Digital] / sumatoria(Venta  12 meses Gráfico + Venta (12 meses) Digital)',
					},
					fields: [
						{
							name: 'pvpPromedio',
							label: 'PVP Promedio: ',
							disabled: true,
							type: 'currency',
							value: 0,
						},
					],
				},
				{
					type: 'wrapper',
					control: 'tooltip',
					name: 'tooltip-porcentaje-venta',
					template: ['1fr'],
					tooltipData: {
						title: 'Porcentaje de Venta 12 meses = (Venta 12 meses / Tirada) * 100',
					},
					fields: [
						{
							name: 'porcentajeVenta12mHeader',
							type: 'traficLight',
							label: '% Vta. (12 m): ',
							disabled: true,
							isPercent: true,
							condition: { red: '', yellow: '', green: '', values: ['porcentajeVenta12M'] },
							parameter: '',
							properties: ['parameter', 'condition', 'color'],
							color: '9',
							decimalsLimit: 0,
							value: 0,
						},
					],
				},
				{
					type: 'wrapper',
					control: 'tooltip',
					name: 'tooltip-porcentaje-margen',
					template: ['1fr'],
					tooltipData: {
						title: 'Porcentaje de Margen Bruto = (Margen Bruto Total / Venta Neta Total) * 100',
					},
					fields: [
						{
							name: 'porcentajeMargenBrutoHeader',
							type: 'traficLight',
							label: '% Margen bruto: ',
							disabled: true,
							isPercent: true,
							condition: { red: '', yellow: '', green: '', values: ['porcentajeMargenBruto'] },
							parameter: '',
							properties: ['parameter', 'condition', 'color'],
							color: '9',
							decimalsLimit: 0,
							value: 0,
						},
					],
				},
				{
					type: 'wrapper',
					control: 'tooltip',
					name: 'tooltip-multiplicador',
					template: ['1fr'],
					tooltipData: {
						title: 'Multiplicador = PVP / Costo Unitario',
					},
					fields: [
						{
							name: 'multiplicadorHeader',
							type: 'traficLight',
							label: 'Multiplicador: ',
							disabled: true,
							condition: { red: '', yellow: '', green: '', values: ['multiplicador'] },
							parameter: '',
							properties: ['parameter', 'condition', 'color'],
							color: '9',
							decimalsLimit: 0,
							value: 0,
						},
					],
				},
				{
					type: 'wrapper',
					control: 'tooltip',
					name: 'tooltip-rentabilidad',
					template: ['1fr'],
					tooltipData: {
						title: 'Rentabilidad = ((Venta Líquida - Inversión Total Título + Inversión Anticipo DA - Fórmula A) / Inversión Total Título) * 100',
					},
					fields: [
						{
							name: 'rentabilidadHeader',
							type: 'traficLight',
							label: 'Rentabilidad: ',
							disabled: true,
							isPercent: true,
							condition: { red: '', yellow: '', green: '', values: ['rentabilidad'] },
							parameter: '',
							properties: ['parameter', 'condition', 'color'],
							color: '9',
							decimalsLimit: 0,
							value: 0,
						},
					],
				},
				{
					type: 'wrapper',
					control: 'tooltip',
					name: 'tooltip-porcentaje-descuento',
					template: ['1fr'],
					tooltipData: {
						title: 'Porcentaje de Descuento aplicado',
					},
					fields: [
						{
							name: 'porcentajeDescuentoHeader',
							type: 'traficLight',
							label: '% Descuento: ',
							disabled: true,
							isPercent: true,
							condition: { red: '', yellow: '', green: '', values: ['porcentajeDescuento'] },
							parameter: '',
							properties: ['parameter', 'condition', 'color'],
							color: '9',
							decimalsLimit: 0,
							value: 0,
						},
					],
				},
				{
					type: 'wrapper',
					control: 'tooltip',
					name: 'tooltip-inversion-total',
					template: ['1fr'],
					tooltipData: {
						title: 'Inversión Total del Título',
					},
					fields: [
						{
							name: 'inversionTotal',
							type: 'currency',
							toFixed: true,
							className: 'with-icon',
							label: 'Inversion total: ',
							value: 0,
							decimalsLimit: 0,
						},
					],
				},
				{
					type: 'wrapper',
					control: 'tooltip',
					name: 'rentability-tooltip2',
					template: ['1fr'],
					className: 'center-tooltip',
					tooltipData: {
						title: 'Rentabilidad ajustada = [sumatoria (Rentabilidad X % * Inversión total) - Inversión adicional] / [sumatoria(Inversión total) + Inversión adicional]',
					},
					fields: [
						{
							disabled: true,
							name: 'porcentajeRentabilidad',
							type: 'traficLight',
							label: 'Rentabilidad ajustada: ',
							isPercent: true,
							condition: { red: '', yellow: '', green: '', values: ['porcentajeRentabilidad'] },
							parameter: '',
							properties: ['parameter', 'condition', 'color'],
							color: '9',
							decimalsLimit: 0,
							value: 0,
						},
					],
				},
			],
		},
		{
			type: 'jViewTitle',
			isVisibleHeader: true,
			entries: [],
			properties: ['entries', 'rows', 'total', 'selectedItem', 'selectedDelete'],
			name: 'titlesTable',
			currentPage: 1,
			rows: 5,
			limitDepdentOnItems: true,
			total: 0,
			showSelect: false,
			className: 'instances-jview firsColumnLargeTitles',
			itemTable: 'titlesTable',
			selectedItem: {},
			selectedDelete: null,
			keys: ['titulo', 'mesAnio', 'pvp', 'tirada', 'porcentajeVenta12M', 'porcentajeMargenBruto', 'inversionTotalTitulo', 'rentabilidad', 'rentabilidadAxPorciento'],
			dataHead: [
				{ label: 'Titulo', id: 1 },
				{ label: 'Mes/Año', id: 2 },
				{ label: 'PVP', id: 3 },
				{ label: 'Tirada', id: 4 },
				{ label: '% Vta. (12 m)', id: 5 },
				{ label: '% Margen bruto', id: 6 },
				{ label: 'Inv. total', id: 7 },
				{ label: 'Rentabilidad', id: 8 },
				{ label: 'Rent. ajustada', id: 9 },
				{ label: ' ', id: 10 },
			],
			textEmpty: 'No existe información para mostrar',
		},
		{
			type: 'button',
			name: 'addButton',
			label: 'Agregar',
			variant: 'primary',
		},
		{ name: 'hr2', type: 'hr' },
		{
			type: 'wrapper',
			control: 'collapsible',
			name: 'titleDataCollapsible',
			opened: false,
			fields: [
				{
					type: 'wrapper',
					control: 'div',
					name: 'contentDiv',
					fields: [
						{
							name: 'titulo',
							type: 'inputText',
							label: 'Título: ',
							value: '',
						},
						{
							name: 'mesAnio',
							type: 'inputDate',
							label: 'Mes/Año: ',
							value: '',
						},
						{
							name: 'pvp',
							type: 'currency',
							label: 'PVP: ',
							value: 0,
						},
						{
							name: 'tirada',
							type: 'number',
							label: 'Tirada: ',
							value: 0,
						},
						{
							name: 'venta12M',
							type: 'number',
							label: 'Venta 12 meses: ',
							value: 0,
						},
						{
							name: 'porcentajeDescuento',
							type: 'percentage',
							label: '% Descuento: ',
							value: 0,
						},
						{
							name: 'porcentajeDerechoAutor',
							type: 'percentage',
							label: '% Derecho Autor: ',
							value: 0,
						},
						{
							name: 'pvpDigital',
							type: 'currency',
							label: 'PVP Digital: ',
							value: 0,
							disabled: true,
						},
						{
							name: 'venta12MDigital',
							type: 'number',
							label: 'Venta 12 meses Digital: ',
							value: 0,
							disabled: true,
						},
						{
							name: 'porcentajeDescuentoDigital',
							type: 'percentage',
							label: '% Descuento Digital: ',
							value: 0,
							disabled: true,
						},
						{
							name: 'porcentajeDerechoAutorDigital',
							type: 'percentage',
							label: '% Derecho Autor Digital: ',
							value: 0,
							disabled: true,
						},
					],
				},
			],
		},
	],
};

